---

- hosts: openttd
  remote_user: root
  tasks:
    - name: Upgrade OS
      apt:
        update_cache: true
        upgrade: true
    - name: Install dependencies
      apt: 
        name: "{{ item }}"
        upgrade: true
        state: present
      with_items:
        - ca-certificates
        - git
        - python-pip
    - name: Clone repository
      git:
        repo: 'https://github.com/defpoint/threat_note.git'
        dest: /opt/threat_note
    - name: Install Python libraries
      pip:
        requirements: /opt/threat_note/requirements.txt
    - name: Copy systemd unit
      template:
        src: files/threat_note.service
        dest: /lib/systemd/system
    - name: Reload systemd
      systemd: daemon_reload=yes
    - name: Enable and start service
      systemd:
        name: threat_note
        state: started
        enabled: true
        masked: no